blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns =[
    # index: localhost:8080
    path('', views.post_list, name='post_list'),

    # localhost:8080/drafts
    path('drafts/', views.post_drafts, name='post_drafts'),

    # localhost:8080/post/ID
    path('post/<int:pk>', views.post_detail, name='post_detail'),

    # localhost:8080/post/new/
    path('post/new/', views.post_new, name='post_new'),

    # localhost:8080/post/ID/edit/
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),

    # localhost:8080/post/ID/publish/
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),

    path('post/<int:pk>/comment/', views.comment_to_a_post, name='comment_to_a_post'),

    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),

    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),

    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),

    path('signup/', views.signup, name='signup'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),

    # localhost:8080/account/login/
    path('login/', auth_views.LoginView.as_view(template_name="registration/login.html"), name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout', ),
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def approved_comments(self):
        return self.comments.filter(approved=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.post', on_delete=models.CASCADE,related_name='comments')
    author = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved = models.BooleanField(default=False)

    def approve_comment(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from crispy_forms.bootstrap import (PrependedText, PrependedAppendedText, FormActions)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','text',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    helper = FormHelper()
    helper.form_method= "POST"
    helper.add_input(Submit("Sign up","Sign up",css_class='btn-primary'))

    class Meta:
        model = User
        fields = ('username','email','password',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib.auth.models import User

from .models import Post, Comment
from .forms import PostForm, CommentForm, UserForm

# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    stuff_for_frontend = {'posts': posts}
    return render(request, 'blog/post_list.html',stuff_for_frontend)

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    stuff_for_frontend = {'post': post}
    return render(request, 'blog/post_detail.html', stuff_for_frontend)

@login_required
def post_new(request):
    #print(request.method)
    # POST
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    # GET
    else:
        form = PostForm()
        stuff_for_frontend = {'form': form}
    return render(request, 'blog/post_edit.html', stuff_for_frontend)

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":

        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)

    else:
        form = PostForm(instance=post)
        stuff_for_frontend = {'form': form}
    return render(request, 'blog/post_edit.html', stuff_for_frontend)

@login_required
def post_drafts(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('-created_date')
    stuff_for_frontend = {'posts': posts}
    return render(request, 'blog/post_drafts.html',stuff_for_frontend)

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=post.pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

@login_required
def comment_to_a_post(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_to_a_post.html', {'form':form})

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve_comment()
    return redirect('blog:post_detail', pk=comment.post.pk)

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            login(request, new_user)
            return redirect('blog:post_list')
    else:
        form = UserForm()
    return render(request, 'registration/signup.html', {'form':form})

blog/templates/blog/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt">

<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link href="https://fonts.googleapis.com/css?family=Fjalla+One|Lato|Luckiest+Guy&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
	<link rel="stylesheet" href="{% static '/blog.css'%}">
	<link rel="stylesheet" href="{% static '/zenburn.css'%}">
	<script src="https://kit.fontawesome.com/b6ca047dfe.js"></script>
</head>
<body>

<div class="page-header">


	<div class="top-menu">
		{% if user.is_authenticated %}
			<h5>Hello {{ user.username }} (<a href="{% url 'logout' %}">Logout</a>)</h5>
			<h1><a href="{% url 'blog:post_new' %}" ><button type="button" class="btn btn-primary">+ New Post</button></a></h1>
			<h1><a href="{% url 'blog:post_drafts' %}" ><button type="button" class="btn btn-primary">Post Drafts</button></a></h1>
		{% else %}
			<h1><a href="{% url 'login' %}" ><button type="button" class="btn btn-primary">Login</button></a></h1>
			<h1><a href="{% url 'blog:signup' %}" ><button type="button" class="btn btn-primary">Signup</button></a></h1>

		{% endif %}
	</div>


	<h1><a href="{% url 'blog:post_list' %}">Eazy Devs BLOG</a></h1>
</div>

<div class="content container">
	<div class="row">
		<div class="col-md-8">

      {% block content %}
      {% endblock %}

    </div>
  </div>
</div>

</body>
</html>

blog/templates/blog/comment_to_a_post.html
{% extends "blog/base.html" %}

{% block title %} Comment Post - {{ comment.post.title }} {% endblock %}

{% block content %}
  <h2>New Comment to Post: {{ post }} </h2>
    <form method="post" class="post-form-blog">
    {% csrf_token %}
    {{ form.as_p }}
    <h1><button type="submit" class="btn btn-primary">Comment</button></h1>
  </form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load markdownify %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
	<div class="post">

		{% if user.is_authenticated %}
		<span class="crud-icons" style="float: right; font-size: 30pt; margin-right: 100px; ">
			{% if not post.published_date %}
				<a href="{% url 'blog:post_publish' pk=post.pk %}"><i class="fas fa-rocket"></i></a>
			{% endif %}
			<a href="{% url 'blog:post_edit' pk=post.pk %}"><i class="fas fa-pencil-alt"></i></a>
			<a href="{% url 'blog:post_remove' pk=post.pk %}"
				onclick="return confirm('Are you sure to delete POST {{ post.title }} ?')"><i class="fas fa-trash"></i></a>
		</span>
		{% endif %}

		<h1>{{ post.title }}</h1>


		{% if post.published_date %}
			<div class="date">
				{{ post.published_date }}
			</div>
		{% endif %}

		<div class="author">
			<h5>Author: {{ post.author}}</h5>
		</div></br>

		<div class="text-desc">
			<p>{{ post.text | markdown | safe | linebreaksbr}}</p>
		</div>

	</div>

	<hr>
	<h5>You can comment on code Language Style as following example:</h5>
	<strong>```python</br>print('Hello World')</br>```</strong></br>
	<hr>

	<a href="{% url 'blog:comment_to_a_post' pk=post.pk  %}" class="btn btn-primary">Comment this Post</a>


		{% for comment in post.comments.all %}
			{% if user.is_authenticated or comment.approved %}

				<div class="comment">
					{% if user.is_superuser %}
						<a href="{% url 'blog:comment_remove' pk=comment.pk %}" class="btn btn-danger"
						onclick="return confirm('Are you sure to delete Comment from  {{ comment.author }} ?')">Delete<a>
					{% endif %}

					{% if not comment.approved and user.is_superuser %}
						<a href="{% url 'blog:comment_approve' pk=comment.pk %}" class="btn btn-danger">Approve<a>
					{% endif %}

					<strong>{{ comment.author}}</strong>

					<div class="date">
						{{ comment.created_date }}
					</div>

					<p>{{ comment.text | markdown | safe | linebreaksbr}}</p>

					<hr>
				</div>
			{% endif %}
		{% empty %}
			<br>
			<h4>No comments yet... <br>Tell us what you think about this Post!</h4>
		{% endfor %}

{% endblock %}

blog/templates/blog/post_drafts.html
{% extends "blog/base.html" %}
{% load markdownify %}

{% block title %} My Drafts {% endblock %}

{% block content %}
  {% for post in posts %}
    <div class="post">

      {% if user.is_authenticated %}
        <span class="crud-icons" style="float: right; font-size: 30pt; margin-right: 100px; ">
          <a href="{% url 'blog:post_publish' pk=post.pk %}"><i class="fas fa-rocket"></i></a>
          <a href="{% url 'blog:post_edit' pk=post.pk %}"><i class="fas fa-pencil-alt"></i></a>
          <a href="{% url 'blog:post_remove' pk=post.pk %}"
          onclick="return confirm('Are you sure to delete POST {{ post.title }} ?')"><i class="fas fa-trash"></i></a>
        </span>
      {% endif %}

      <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>

      <div class="date">
        <h5>Published: {{ post.published_date }}</h5>
      </div>

      <div class="text-desc">
        <p>{{ post.text|truncatechars:150 |markdown | safe |linebreaksbr }}</p>
      </div>

    </div>
  {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends "blog/base.html" %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}

  {% if not user.is_authenticated %}
    <p><h1>!!!User is not authenticated!!!</h1></p>
  {% endif %}

  {% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
  {% endif %}

  {% if user.is_authenticated %}
    <h1>New Post</h1>
    <form method="post" class="post-form-blog">
      {% csrf_token %}
      {{ form.as_p }}
      <h1><a href="{% url 'blog:post_list' %}" ><button type="button" class="btn btn-primary">Cancel</button></a></h1>
      <h1><button type="submit" class="btn btn-primary">Save</button></h1>
    </form>
  {% endif %}

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% load markdownify %}

{% block content %}

	{% for post in posts %}
		<div class="post">
			<div class="post-texts">
				{% if user.is_authenticated %}
					<span class="crud-icons" style="float: right; font-size: 20pt; margin-right: 100px; ">
						<a href="{% url 'blog:post_edit' pk=post.pk %}"><i class="fas fa-pencil-alt"></i></a>
				 		<a href="{% url 'blog:post_remove' pk=post.pk %}"
							onclick="return confirm('Are you sure to delete POST {{ post.title }} ?')"><i class="fas fa-trash"></i></a>
					</span>
				{% endif %}

				<h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>

				<div class="date">
					<h5>Published: {{ post.published_date }}</h5>
				</div>

				<div class="text-desc">
					<p>{{ post.text|truncatechars:200 |markdown | safe |linebreaksbr }}</p>
				</div>
				<h1><a href="{% url 'blog:post_detail' pk=post.pk %}" class="btn btn-primary">Read More . . .</button></a></h1>
				<a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count}}</button></a>
			</div>
		</div>
	{% endfor %}

{% endblock %}